CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y

CONFIG_SHELL=n
CONFIG_GPIO_SHELL=n

CONFIG_EVENTS=y

CONFIG_WATCHDOG=y
CONFIG_ADC=y
CONFIG_GPIO=y
CONFIG_CLOCK_CONTROL=y
CONFIG_KEEPALIVE=n

# The options below reduce flash usage
CONFIG_SIZE_OPTIMIZATIONS_AGGRESSIVE=y
CONFIG_BOOT_BANNER=n
CONFIG_THREAD_NAME=n
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_MEM_SLAB_TRACE_MAX_UTILIZATION=n
CONFIG_UART_USE_RUNTIME_CONFIGURE=n
CONFIG_CBPRINTF_NANO=y
CONFIG_CBPRINTF_FP_A_SUPPORT=n
CONFIG_CBPRINTF_REDUCED_INTEGRAL=y
CONFIG_CBPRINTF_LIBC_SUBSTS=n
CONFIG_THREAD_ANALYZER=y
CONFIG_SENSOR_ASYNC_API=n
CONFIG_DP_BOARD_SHELL=n
CONFIG_ASSERT_VERBOSE=n

CONFIG_SHELL_PROMPT_CHANGE=n
CONFIG_SHELL_CMDS=n
CONFIG_SHELL_TAB=n
CONFIG_SHELL_WILDCARD=n
CONFIG_SHELL_VT100_COLORS=n
CONFIG_SHELL_HELP=n
CONFIG_SHELL_HISTORY=n
CONFIG_SHELL_STATS=n
CONFIG_DEVICE_SHELL=n
CONFIG_COMPARATOR_SHELL=n

CONFIG_DP_METRICS=y
CONFIG_DMA=y
CONFIG_UART_ASYNC_API=y

CONFIG_BINDESC=y
CONFIG_BINDESC_DEFINE=y
CONFIG_BINDESC_DEFINE_VERSION=y
CONFIG_BINDESC_APP_VERSION_MAJOR=y
CONFIG_BINDESC_APP_VERSION_MINOR=y
CONFIG_BINDESC_APP_VERSION_PATCHLEVEL=y

CONFIG_BINDESC_DP_APP_VERSION_BUILD=y
CONFIG_BINDESC_DP_SW_PART_NUMBER=y

CONFIG_REBOOT=y

CONFIG_CONSOLE=y

CONFIG_ECP_DEVICE_CMD_DEDICATED_THREAD=y

CONFIG_DP_PORTS_HANDLER_DEDICATED_THREAD=n
