#include <zephyr/kernel.h>
#include <zephyr/version.h>

#include <dp/dp-bindesc.h>

#include <zephyr/app_version.h>

#if defined(CONFIG_BINDESC_DP_APP_VERSION_BUILD)
BINDESC_UINT_DEFINE(dp_app_version_build, BINDESC_ID_DP_APP_VERSION_BUILD, APP_TWEAK);
#endif // CONFIG_BINDESC_DP_APP_VERSION_BUILD

#if defined(CONFIG_BINDESC_DP_SW_PART_NUMBER)
BINDESC_STR_DEFINE(dp_sw_part_number, BINDESC_ID_DP_SW_PART_NUMBER, CONFIG_APP_ECP_SW_PART_NUMBER);
#endif // CONFIG_BINDESC_DP_SW_PART_NUMBER

#define GIT_HASH CONCAT("-" STRINGIFY(APP_BUILD_VERSION))

#if defined(CONFIG_BINDESC_DP_APP_VERSION_STRING)
BINDESC_STR_DEFINE(dp_app_version_string, BINDESC_ID_DP_APP_VERSION_STRING,
		   APP_VERSION_EXTENDED_STRING GIT_HASH);
#endif // CONFIG_BINDESC_DP_APP_VERSION_STRING
